# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProject\pythonQt\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(390, 360, 75, 23))
        self.btn_start.setObjectName("btn_start")
        self.btn_app = QtWidgets.QPushButton(self.centralwidget)
        self.btn_app.setEnabled(True)
        self.btn_app.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.btn_app.setObjectName("btn_app")
        self.textEdit_apppath = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_apppath.setEnabled(False)
        self.textEdit_apppath.setGeometry(QtCore.QRect(130, 60, 331, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.textEdit_apppath.setFont(font)
        self.textEdit_apppath.setObjectName("textEdit_apppath")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(20, 100, 78, 29))
        self.text.setObjectName("text")
        self.textEdit_packagename = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_packagename.setGeometry(QtCore.QRect(130, 100, 331, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.textEdit_packagename.setFont(font)
        self.textEdit_packagename.setObjectName("textEdit_packagename")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 51, 29))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 81, 29))
        self.label.setObjectName("label")
        self.edit_times = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_times.setGeometry(QtCore.QRect(90, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.edit_times.setFont(font)
        self.edit_times.setObjectName("edit_times")
        self.edit_div = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_div.setGeometry(QtCore.QRect(300, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.edit_div.setFont(font)
        self.edit_div.setObjectName("edit_div")
        self.btn_scan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scan.setGeometry(QtCore.QRect(280, 360, 75, 23))
        self.btn_scan.setObjectName("btn_scan")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 150, 441, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.device_checkbox0 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_checkbox0.setObjectName("device_checkbox0")
        self.horizontalLayout.addWidget(self.device_checkbox0)
        self.device_progressBar0 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.device_progressBar0.setProperty("value", 0)
        self.device_progressBar0.setObjectName("device_progressBar0")
        self.horizontalLayout.addWidget(self.device_progressBar0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 190, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.device_checkbox1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.device_checkbox1.setObjectName("device_checkbox1")
        self.horizontalLayout_2.addWidget(self.device_checkbox1)
        self.device_progressBar1 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.device_progressBar1.setProperty("value", 0)
        self.device_progressBar1.setObjectName("device_progressBar1")
        self.horizontalLayout_2.addWidget(self.device_progressBar1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 230, 441, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.device_checkbox2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.device_checkbox2.setObjectName("device_checkbox2")
        self.horizontalLayout_3.addWidget(self.device_checkbox2)
        self.device_progressBar2 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.device_progressBar2.setProperty("value", 0)
        self.device_progressBar2.setObjectName("device_progressBar2")
        self.horizontalLayout_3.addWidget(self.device_progressBar2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 270, 441, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.device_checkbox3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.device_checkbox3.setObjectName("device_checkbox3")
        self.horizontalLayout_4.addWidget(self.device_checkbox3)
        self.device_progressBar3 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_4)
        self.device_progressBar3.setProperty("value", 0)
        self.device_progressBar3.setObjectName("device_progressBar3")
        self.horizontalLayout_4.addWidget(self.device_progressBar3)
        self.btn_start.raise_()
        self.btn_app.raise_()
        self.textEdit_apppath.raise_()
        self.text.raise_()
        self.textEdit_packagename.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.edit_times.raise_()
        self.edit_div.raise_()
        self.btn_scan.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.device_progressBar2.raise_()
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "start"))
        self.btn_app.setText(_translate("MainWindow", "Choose App:"))
        self.text.setText(_translate("MainWindow", " Package Name:"))
        self.label_2.setText(_translate("MainWindow", " times:    "))
        self.label.setText(_translate("MainWindow", "  div(ms):"))
        self.btn_scan.setText(_translate("MainWindow", "scan"))
        self.device_checkbox0.setText(_translate("MainWindow", "CheckBox"))
        self.device_checkbox1.setText(_translate("MainWindow", "CheckBox"))
        self.device_checkbox2.setText(_translate("MainWindow", "CheckBox"))
        self.device_checkbox3.setText(_translate("MainWindow", "CheckBox"))

